#!/usr/bin/env bash
set -euxo pipefail

sudo -n ls || (echo "Must be run as root" && exit 1)

PROJECT_DIR=$1
SECRETS_REPO=$2

REPO_DIR=/repos

mkdir -p "$REPO_DIR"
git clone https://github.com/mrichtarsky/linux-shared.git "$REPO_DIR/linux-shared"
git clone "$SECRETS_REPO" "$REPO_DIR/secrets"

addgroup linux-shared
chown -R root:linux-shared "$REPO_DIR"
chmod -R 660 "$REPO_DIR"

rm /r
ln -s "$REPO_DIR/linux-shared" /r

pushd /r

git submodule init
git submodule update

mkdir -p $PROJECT_DIR
chmod a+rwx $PROJECT_DIR
rm /p || true
ln -s $PROJECT_DIR /p

mkdir -p /p/tools

PACKAGES="expect git htop mc nano ncdu python3 ripgrep sysstat tmux"
DISTRO=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }')

echo "Distribution: $DISTRO"

if [ "$DISTRO" == sles ];
then
    zypper install $PACKAGES python3-pip
else
    apt install $PACKAGES
fi

wget https://dystroy.org/broot/download/x86_64-linux/broot
chmod a+x broot
mv broot /usr/local/bin/broot

python3 -m pip install pypyp

/r/_impl/setup_rust

export RUSTUP_HOME=/p/tools/rust
export CARGO_HOME=/p/tools/rust/.cargo
source /p/tools/rust/.cargo/env

cargo install git-delta
chmod a+rx -R /p/tools/rust/.cargo

# VSCode watches
WATCHES=fs.inotify.max_user_watches=524288
grep -qF $WATCHES /etc/sysctl.conf || echo "$WATCHES" >>/etc/sysctl.conf
sysctl -p

python3 -m pip install telegram-send

CRON_CLEAN="00 05 * * * /r/s/cronic /r/cronjobs/clean_disk_caches"
((crontab -l | grep -v clean_disk_caches); echo "$CRON_CLEAN") | crontab -

CRON_PULL="10 05 * * * /r/s/cronic /r/cronjobs/pull /r"
((crontab -l | grep -v pull); echo "$CRON_PULL") | crontab -

CRON_IS_REPO_CLEAN="08 05 * * * /r/s/cronic /r/cronjobs/is_repo_clean /r"
((crontab -l | grep -v is_repo_clean); echo "$CRON_IS_REPO_CLEAN") | crontab -

popd

echo "OK"
