#!/usr/bin/env bash
set -euo pipefail

# Specify files/directories to include in .shellcheck_excludes

EXCLUDE_FILE=.shellcheck_excludes
if [ ! -f "$EXCLUDE_FILE" ]; then
    EXCLUDE_FILE=/dev/null
fi

# -x tries to follow files. In some cases this is not possible,
# so ignore the resulting SC1091.

# shellcheck disable=SC2046
shellcheck -e SC1090,SC1091,SC2002 -x $(grep -rl '^#!/.*bash' . | grep -v -f "$EXCLUDE_FILE")
