#!/usr/bin/env bash
set -euo pipefail

# Specify files/directories to exclude in .shellcheck_excludes

EXCLUDE_FILE=.shellcheck_excludes
if [ ! -f "$EXCLUDE_FILE" ]; then
    EXCLUDE_FILE=/dev/null
fi

FILES=$({ grep -rl '^#!/.*bash' .; find . -name '*\.sh'; } \
        | (grep -v /.git/ || true) \
        | (grep -v -f "$EXCLUDE_FILE" || true) )
if [ -n "$FILES" ]; then
    # -x tries to follow files. In some cases this is not possible,
    # so ignore the resulting SC1091.
    # shellcheck disable=SC2086
    shellcheck -e SC1090,SC1091,SC2002 -x $FILES
fi
