#!/usr/bin/env python3

import sys
from getpass import getpass

from argon2 import PasswordHasher

password = getpass("Password: ")
password2 = getpass("Verify: ")

if password != password2:
    print("MISMATCH!")
    sys.exit(1)

argon2Hasher = PasswordHasher()
print(argon2Hasher.hash(password))
