#!/usr/bin/env bash
set -euxo pipefail

# Clean tmp
find /tmp \( -name 'pyright*' -o -name 'lessphp*cache' -o -name 'vscode*sock' -o -name 'tmp*' -o -name '.org.chromium.Chromium*' \) -mtime +30 -exec rm -rf {} \; || true

# These are not needed anymore, stored just for reference, but fill up disk.
# Keep last 90 days just in case.

if [ -d /etc/letsencrypt/csr ]; then
    find /etc/letsencrypt/csr -type f -name '*.pem' -mtime +14 -exec rm -f {} \;
fi
if [ -d /etc/letsencrypt/keys ]; then
    find /etc/letsencrypt/keys -type f -name '*.pem' -mtime +14 -exec rm -f {} \;
fi

if [[ "$OSTYPE" =~ ^darwin ]];
then
    exit 0
fi

DISTRO=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }')

echo "$DISTRO"
if [ "$DISTRO" == ubuntu ];
then
    apt clean
    rm -rf ~/.cache
fi
