#!/usr/bin/env bash
set -euxo pipefail

if [[ "$OSTYPE" =~ ^darwin ]];
then
    exit 0
fi

DISTRO=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }')

echo "$DISTRO"
if [ "$DISTRO" == ubuntu ];
then
    apt clean
    rm -rf ~/.cache
fi
