#!/bin/bash

# Cronic v3 - cron job report wrapper
# Copyright 2007-2016 Chuck Houpt. No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/

# Get standard paths etc.
# Avoid error from scripts assuming interactive shell
function bind() { :; }
source /etc/profile

set -eu

TMP=$(mktemp -d)
OUT=$TMP/cronic.out
TRACE=$TMP/cronic.trace

set +e
"$@" >"$OUT" 2>"$TRACE"
RESULT=$?
set -e

if [ $RESULT -ne 0 ]
    then
    echo "Cronic detected failure or error output for the command:"
    echo "$@"
    echo
    echo "RESULT CODE: $RESULT"
    echo
    echo "ERROR OUTPUT:"
    cat "$TRACE"
    echo
    echo "ENVIRONMENT:"
    env
    echo
    echo "STANDARD OUTPUT:"
    cat "$OUT"
fi

rm -rf "$TMP"
