#!/bin/bash

# Cronic v3 - cron job report wrapper
# Copyright 2007-2016 Chuck Houpt. No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/

# Get standard paths etc.
# Avoid error from scripts assuming interactive shell
#function bind() { :; }

source ~/.bash_profile  # On SLES, this will pull in local environment.
                        # Debian/Ubuntu skip this in non-interactive shell.
source /r/_init.sh

set -eu

TMP=$(mktemp -d)
OUT=$TMP/cronic.out
ERR=$TMP/cronic.err
TRACE=$TMP/cronic.trace

set +e
"$@" >"$OUT" 2>"$TRACE"
RESULT=$?
set -e

PATTERN="^${PS4:0:1}\\+${PS4:1}"
if grep -aq "$PATTERN" "$TRACE"
then
    grep -av "$PATTERN" "$TRACE" > "$ERR" && exit 1
else
    ERR=$TRACE
fi

if [ $RESULT -ne 0 ] || [ -s "$ERR" ]
    then
    echo "Cronic detected failure or error output for the command:"
    echo "$@"
    echo
    echo "RESULT CODE: $RESULT"
    echo
    echo "ERROR OUTPUT:"
    cat "$ERR"
    echo
    echo "STANDARD OUTPUT:"
    cat "$OUT"
    if [ "$TRACE" != "$ERR" ]
    then
        echo
        echo "TRACE-ERROR OUTPUT:"
        cat "$TRACE"
    fi
    echo
    echo "ENVIRONMENT:"
    env
fi

rm -rf "$TMP"
