#!/usr/bin/env bash
set -euo pipefail

if [[ "$OSTYPE" =~ ^darwin ]]; then
    SPOOL=/var/mail
else
    SPOOL=/var/spool/mail
fi

find -L "$SPOOL" -type f -size +0 -print0 | xargs -0 --no-run-if-empty ls -al
