#!/usr/bin/env python3

'''
Automatically extract data from your inbox

Define the following in /repos/secrets/inbox_parser_config.py:

# Servers to query
SERVERS = (
    { 'host': 'xxx', 'login': 'xxx', 'password': 'xxx', },
    ...
)

# Cutoff date, only messages at or after that date are checked
SINCE_DATE = datetime.date.today().strftime("%d-%b-%Y")

# Filter for subject
SUBJECT_SEARCHSTRING = ''

DELETE_HANDLED = False

def handler(msg):
    Called for every message in the inbox.
    Search and extract desired data here.

    Return True when the message has been
    processed and can be deleted, False otherwise.
'''

from mail.tools import search_inbox
from tools.misc import eprint

# secrets repo since it contains credentials
import sys
sys.path.append('/repos/secrets')
from inbox_parser_config import SERVERS, SINCE_DATE, SUBJECT_SEARCHSTRING, DELETE_HANDLED, handler  # pylint: disable=wrong-import-position

for server in SERVERS:
    eprint('Checking', server)

    search_inbox(server['host'], server['login'], server['password'],
                SINCE_DATE, SUBJECT_SEARCHSTRING, handler, DELETE_HANDLED)
