#!/usr/bin/env python3

import getpass
import sys

from tools.lib.keyring_setup import cryptfile_keyring
from tools.misc import confirm

if len(sys.argv) != 3:
    print(f'Usage: {sys.argv[0]} system user')
    sys.exit(1)

_, system, user = sys.argv  # pylint: disable=unbalanced-tuple-unpacking

if (password := cryptfile_keyring.get_password(system, user)) is not None:
    print('Warning: Password already present!')
    if confirm('Show?'):
        print(password)
    if not confirm('Overwrite?'):
        sys.exit(0)

password = getpass.getpass('Password: ')
cryptfile_keyring.set_password(system, user, password)

print('OK')
