#!/usr/bin/env python3

import sys

from tools.secrets import credentials

try:
    system, what = sys.argv[1:3]
except ValueError:
    print("Usage: keyring_get system user|password")
    sys.exit(1)

print(credentials[system][what])
