#!/usr/bin/env python3
import socket
import sys

import telegram_send

text = '\n'.join(sys.argv[1:])
message = f"{socket.gethostname()}:\n{text}"
telegram_send.send(conf='~/.secrets/telegram.conf', messages=[message])
