#!/usr/bin/env python3
import asyncio
import socket
import sys

import telegram_send

text = '\n'.join(sys.argv[1:])
message = f'{socket.gethostname()}:\n{text}'
asyncio.run(telegram_send.send(conf='~/.secrets/telegram.conf', messages=[message]))
