#!/usr/bin/env python3
import telegram_send

import socket
import sys

text = '\n'.join(sys.argv[1:])
message = f"{socket.gethostname()}:\n{text}"
telegram_send.send(conf='~/.credentials/telegram.conf', messages=[message])
