#!/usr/bin/env bash
set -euxo pipefail

REPO_BASE_PATH=/repos

function fix_perms_for_repo {
    REPO_PATH="${REPO_BASE_PATH}/${1}"
    if [ -d "$REPO_PATH" ]; then
        chown -R root:linux-shared "$REPO_PATH"
        chmod -R g=u,o= "$REPO_PATH"
        # When running as root, git will recreate the index file and others with group root
        # by default. Set gid on directories to prevent that.
        find "${REPO_PATH}/" -type d -exec chmod g+s {} +
    fi
}

fix_perms_for_repo linux-shared
LINUX_SHARED="$REPO_BASE_PATH/linux-shared"
chmod 664 "${LINUX_SHARED}/setup/_impl/files/sitecustomize.py"
chmod 775 "${LINUX_SHARED}/setup/_impl/files/ll"
chmod -R o=rX "${LINUX_SHARED}/lib"
chmod o=rX "${LINUX_SHARED}"

fix_perms_for_repo secrets
