#!/usr/bin/env bash
set -euxo pipefail

REPO_PATH=/repos
chown -R root:linux-shared "$REPO_PATH/linux-shared"
chmod -R o=rx,g=u "$REPO_PATH/linux-shared"
chmod -R o+rx "$REPO_PATH/linux-shared/lib"
if [[ -d "$REPO_PATH/secrets" ]]; then
    chmod -R o-rwx,g=u "$REPO_PATH/secrets"
chown -R root:linux-shared "$REPO_PATH/secrets"
fi
chmod a+r "$REPO_PATH/linux-shared/setup/_impl/sitecustomize.py"
