#!/usr/bin/env bash
set -euox pipefail

if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

USER=$1

usermod -a -G linux-shared "$USER"
su - "$USER" /r/setup/_impl/install_for_user "$USER"

echo "OK"
