#!/usr/bin/env bash
set -euox pipefail

source /r/setup/_impl/tools.sh

if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

USER=$1

if [[ "$OSTYPE" =~ ^darwin ]];
then
    dseditgroup -o edit -a $USER -t user linux-shared
else
    usermod -a -G linux-shared "$USER"
    add_if_not_present /etc/security/limits.conf "$USER hard nofile 1048576"
    add_if_not_present /etc/security/limits.conf "$USER soft nofile 1048576"
fi

su - "$USER" /r/setup/_impl/install_for_user "$USER"

echo "OK"
