#!/usr/bin/env bash
set -euxo pipefail

source /r/setup/_impl/tools.sh

pushd /r

user=$(whoami)

if [[ "$OSTYPE" =~ ^darwin ]];
then
    /usr/bin/chsh -s /opt/homebrew/bin/bash
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    add_if_not_present ~/.bash_profile 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    eval "$(/opt/homebrew/bin/brew shellenv)"
    brew tap espanso/espanso
    brew install bash broot btop coreutils duf espanso fd fswatch fzf gawk gron gsed htop jesseduffield/lazydocker/lazydocker mc moreutils nano ncdu ripgrep shellcheck tmux ugrep
fi

if [[ "$OSTYPE" =~ ^darwin ]];
then
    "$(brew --prefix)/opt/fzf/install"
else
    rm -rf ~/.fzf
    cp -r /r/env/fzf ~/.fzf
    ~/.fzf/install --all
    # Disable so fzf-obc can take over
    perl -pi -e 's/(^.*?source.*?shell\/completion.bash.*?$)/#\1/' ~/.fzf.bash
fi

echo "Linking configuration"
cd ~
mkdir -p configbackup
for f in .config .gitconfig .gitconfig-linux .gitconfig-macos .inputrc .tmux.conf
do
    rm "configbackup/$f.tar" || true
    tar -c -f "configbackup/$f.tar" --dereference "$f" || true
    rm -rf "$f"
    ln -s "/r/homedir/$f" .
done

rm -rf .secrets
ln -s /repos/secrets/ .secrets

chmod u+w ~/.profile

add_if_not_present ~/.bash_profile '. ~/.bashrc'

if [[ "$OSTYPE" =~ ^darwin ]];
then

    rm ~/Library/Application\ Support/Code/User/keybindings.json || true
    ln -s /r/configs/vscode/keybindings.json ~/Library/Application\ Support/Code/User/
fi

add_if_not_present ~/.bashrc '. /r/_init.sh'

if [[ ! "$OSTYPE" =~ ^darwin ]];
then
    DISTRO=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }')
    if [ "$DISTRO" == '"ubuntu"' ];
    then
        add_if_not_present ~/.bashrc '. /etc/bash_completion'
    fi
else
    add_cronjob "brew_update" "01 00 * * * /r/s/cronic /r/setup/brew_update"
fi

cp /r/setup/USER_VERSION "/r/setup/state/users/${user}_VERSION"

popd
