#!/usr/bin/env bash
set -euxo pipefail

source /r/setup/_impl/tools.sh

pushd /r

user=$(whoami)

if [[ "$OSTYPE" =~ ^darwin ]];
then
    /usr/bin/chsh -s /opt/homebrew/bin/bash
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    add_if_not_present ~/.bash_profile 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    eval "$(/opt/homebrew/bin/brew shellenv)"
    brew tap espanso/espanso
    brew install bash broot coreutils espanso fd fzf gawk gron gsed htop mc moreutils nano ncdu ripgrep shellcheck tmux ugrep
fi

if [[ "$OSTYPE" =~ ^darwin ]];
then
    "$(brew --prefix)/opt/fzf/install"
else
    rm -rf ~/.fzf
    cp -r /r/env/fzf ~/.fzf
    ~/.fzf/install --all
fi

echo "Linking configuration"
cd ~
mkdir -p configbackup
for f in .config .gitconfig .inputrc .tmux.conf
do
    rm "configbackup/$f.tar"
    tar cfL "configbackup/$f.tar" "$f" || true
    ln -s "/r/homedir/$f" .
done

rm -rf .secrets
ln -s /repos/secrets/ .secrets

chmod u+w ~/.profile

if [[ "$OSTYPE" =~ ^darwin ]];
then
    add_if_not_present ~/.bash_profile '. ~/.bashrc'
fi

add_if_not_present ~/.bash_profile '. /r/_init.sh'

cp /r/setup/USER_VERSION "/r/setup/state/users/${user}_VERSION"

popd
