#!/usr/bin/env bash
set -eufo pipefail

_FZF_COMPLETION_SEP=$'\x01'

ITEM=${1/$_FZF_COMPLETION_SEP/}

([ -d "$ITEM" ] && lsd --color=always --icon=always -al "$ITEM") || (lsd -al --color=always --icon=always "$ITEM" && echo && bat --color=always --style=numbers --line-range=:500 "$ITEM")
