#!/usr/bin/env bash
set -euo pipefail

if tmux list-sessions 2>/dev/null | grep window &>/dev/null
then
    export "`tmux showenv PATH`"
    if [[ ! "$OSTYPE" =~ ^darwin ]];
    then
        export "`tmux showenv VSCODE_IPC_HOOK_CLI`"
    fi
fi

ARGS="$@"
MCEDIT_ARGS="" # Remove -w if present
for arg do
  shift
  [ "$arg" = "-w" ] && continue
  MCEDIT_ARGS="$MCEDIT_ARGS $arg"
done
MCEDIT_ARGS="${MCEDIT_ARGS## }"

code "$ARGS" &>/dev/null || mcedit "$MCEDIT_ARGS"
